export const localeText = {
    page: "صفحه",
    more: "بیشتر",
    to: "تا",
    of: "از",
    next: "بعدی",
    last: "آخرین",
    first: "اولین",
    previous: "قبلی",
    loadingOoo: "در حال بارگذاری...",
    selectAll: "انتخاب همه",
    searchOoo: "جستجو...",
    blank: "خالی",
    notBlank:"خالی نباشد",
    filterOoo: "فیلتر...",
    applyFilter: "اعمال فیلنر...",
    equals: "برابر",
    notEqual: "نابرابر",
    lessThan: "کمتر از",
    greaterThan: "بیشتر از",
    lessThanOrEqual: "کمتر مسائری",
    greaterThanOrEqual: "بیشتر مساوی",
    inRange: "در محدوده",
    contains: "شامل",
    notContains: "شامل نمی شود",
    startsWith: "شروع با",
    endsWith: "پایان با",
    andCondition: "شرط",
    orCondition: "daOR",
    group: "laGroup",
    columns: "laColumns",
    filters: "laFilters",
    rowGroupColumns: "laPivot Cols",
    rowGroupColumnsEmptyMessage: "la drag cols to group",
    valueColumns: "laValue Cols",
    pivotMode: "laPivot-Mode",
    groups: "laGroups",
    values: "laValues",
    pivots: "laPivots",
    valueColumnsEmptyMessage: "la drag cols to aggregate",
    pivotColumnsEmptyMessage: "la drag here to pivot",
    toolPanelButton: "la tool panel",
    noRowsToShow: "داده ای وجود ندارد",
    enabled: "laEnabled",
    pinColumn: "سنجاق زدن",
    valueAggregation: "laValue Agg",
    autosizeThiscolumn: "اندازه خودکار این ستون",
    autosizeAllColumns: "اندازه خودکار همه ستون ها",
    groupBy: "گروهبندی",
    ungroupBy: "laUnGroup by",
    resetColumns: "تنظیم مجدد ستونها",
    expandAll: "laOpen-em-up",
    collapseAll: "laClose-em-up",
    toolPanel: "laTool Panelo",
    export: "خروجی",
    csvExport: "ذخیره CSV",
    excelExport: "ذخبره اکسل (.xlsx)",
    excelXmlExport: "ذخبره اکسل (.xml)",
    pivotChartAndPivotMode: "laPivot Chart & Pivot Mode",
    pivotChart: "laPivot Chart",
    chartRange: "laChart Range",
    columnChart: "laColumn",
    groupedColumn: "laGrouped",
    stackedColumn: "laStacked",
    normalizedColumn: "la100% Stacked",
    barChart: "laBar",
    groupedBar: "laGrouped",
    stackedBar: "laStacked",
    normalizedBar: "la100% Stacked",
    pieChart: "laPie",
    pie: "laPie",
    doughnut: "laDoughnut",
    line: "laLine",
    xyChart: "laX Y (Scatter)",
    scatter: "laScatter",
    bubble: "laBubble",
    areaChart: "laArea",
    area: "laArea",
    stackedArea: "laStacked",
    normalizedArea: "la100% Stacked",
    pinLeft: "سنجاق به &lt;&lt;",
    pinRight: "سنجاق به &gt;&gt;",
    noPin: "سنجاق به &lt;&gt;",
    sum: "laSum",
    min: "laMin",
    max: "laMax",
    none: "laNone",
    count: "laCount",
    average: "laAverage",
    filteredRows: "فیلتر شده ها",
    selectedRows: "laSelected",
    totalRows: "تعداد کل",
    totalAndFilteredRows: "تعداد سطر بعد از فیلتر",
    copy: "کپی",
    copyWithHeaders: "کپی با هدر",
    ctrlC: "ctrl + C",
    paste: "الصاق",
    ctrlV: "ctrl + V",
    pivotChartTitle: "laPivot Chart",
    rangeChartTitle: "laRange Chart",
    settings: "laSettings",
    data: "laData",
    format: "laFormat",
    categories: "laCategories",
    series: "laSeries",
    xyValues: "laX Y Values",
    paired: "laPaired Mode",
    axis: "laAxis",
    color: "laColor",
    thickness: "laThickness",
    xRotation: "laX Rotation",
    yRotation: "laY Rotation",
    ticks: "laTicks",
    width: "laWidth",
    length: "laLength",
    padding: "laPadding",
    chart: "laChart",
    title: "laTitle",
    background: "laBackground",
    font: "laFont",
    top: "laTop",
    right: "laRight",
    bottom: "laBottom",
    left: "laLeft",
    labels: "laLabels",
    size: "laSize",
    minSize: "laMinimum Size",
    maxSize: "laMaximum Size",
    legend: "laLegend",
    position: "laPosition",
    markerSize: "laMarker Size",
    markerStroke: "laMarker Stroke",
    markerPadding: "laMarker Padding",
    itemPaddingX: "laItem Padding X",
    itemPaddingY: "laItem Padding Y",
    strokeWidth: "laStroke Width",
    offset: "laOffset",
    offsets: "laOffsets",
    tooltips: "laTooltips",
    callout: "laCallout",
    markers: "laMarkers",
    shadow: "laShadow",
    blur: "laBlur",
    xOffset: "laX Offset",
    yOffset: "laY Offset",
    lineWidth: "laLine Width",
    normal: "laNormal",
    bold: "laBold",
    italic: "laItalic",
    boldItalic: "laBold Italic",
    predefined: "laPredefined",
    fillOpacity: "laFill Opacity",
    strokeOpacity: "laLine Opacity",
    columnGroup: "laColumn",
    barGroup: "laBar",
    pieGroup: "laPie",
    lineGroup: "laLine",
    scatterGroup: "laScatter",
    areaGroup: "laArea",
    groupedColumnTooltip: "laGrouped",
    stackedColumnTooltip: "laStacked",
    normalizedColumnTooltip: "la100% Stacked",
    groupedBarTooltip: "laGrouped",
    stackedBarTooltip: "laStacked",
    normalizedBarTooltip: "la100% Stacked",
    pieTooltip: "laPie",
    doughnutTooltip: "laDoughnut",
    lineTooltip: "laLine",
    groupedAreaTooltip: "laGrouped",
    stackedAreaTooltip: "laStacked",
    normalizedAreaTooltip: "la100% Stacked",
    scatterTooltip: "laScatter",
    bubbleTooltip: "laBubble",
    noDataToChart: "laNo data available to be charted.",
    pivotChartRequiresPivotMode: "laPivot Chart requires Pivot Mode enabled."
}
